/*
 * @Author: pythonkd 1181878670@qq.com
 * @Date: 2026-07-12 16:12:47
 * @LastEditors: pythonkd 1181878670@qq.com
 * @LastEditTime: 2026-08-12 22:38:50
 * @FilePath: /swift_riscv/rtl/swift_riscv_defines.v
 * @Description: 
 * 
 * Copyright (c) 2026 by  kunpeng.zhao, All Rights Reserved. 
 */
// simulation clock period
`define SIM_PERIOD 20 // 20ns -> 50MHz 

`define REG_WIDTH 32

`define INST_JUMP_WIDTH 2
`define INST_JUMP_JAL `INST_JUMP_WIDTH'b01
`define INST_JUMP_JALR `INST_JUMP_WIDTH'b10
`define INST_JUMP_B `INST_JUMP_WIDTH'b11

`define INST_WIDTH 32
`define INST_MEM_DEPTH 4096
`define INST_MEM_WIDTH 12 // 2^10=1024

`define REG_DATA_DEPTH 32
`define DATA_MEM_DEPTH 4096
`define DATA_MEM_WIDTH 16 // 2^10=1024

`define INST_OPCODE_WIDTH 7
`define INST_OPCODE_BASE 0
`define INST_RD_WIDTH 5
`define INST_RD_BASE 7
`define INST_FUNC3_WIDTH 3
`define INST_FUNC3_BASE 12
`define INST_RS1_WIDTH 5
`define INST_RS1_BASE 15
`define INST_RS2_WIDTH 5
`define INST_RS2_BASE 20
`define INST_RL_BASE 25
`define INST_AQ_BASE 26
`define INST_FUNC5_WIDTH 5
`define INST_FUNC5_BASE 27
`define INST_FUNC7_WIDTH 7
`define INST_FUNC7_BASE 25

`define INST_OPCODE_I_TYPE `INST_OPCODE_WIDTH'b0010011
`define INST_OPCODE_I_ADDI `INST_FUNC3_WIDTH'b0
`define INST_OPCODE_I_XORI `INST_FUNC3_WIDTH'b100
`define INST_OPCODE_I_ORI `INST_FUNC3_WIDTH'b110
`define INST_OPCODE_I_ANDI `INST_FUNC3_WIDTH'b111
`define INST_OPCODE_I_SLLI `INST_FUNC3_WIDTH'b001
`define INST_OPCODE_I_SLTI `INST_FUNC3_WIDTH'b010
`define INST_OPCODE_I_SLTIU `INST_FUNC3_WIDTH'b011
`define INST_OPCODE_I_SR `INST_FUNC3_WIDTH'b101
//func7 00
`define INST_I_FUNC7_BASE_TYPE0 `INST_FUNC7_WIDTH'h0
`define INST_OPCODE_I_SRLI `INST_FUNC3_WIDTH'b101
//func7 20
`define INST_I_FUNC7_BASE_TYPE1 `INST_FUNC7_WIDTH'h20
`define INST_OPCODE_I_SRAI `INST_FUNC3_WIDTH'b101


`define INST_OPCODE_IL_TYPE `INST_OPCODE_WIDTH'b0000011
`define INST_OPCODE_IL_LB `INST_FUNC3_WIDTH'b000
`define INST_OPCODE_IL_LH `INST_FUNC3_WIDTH'b001
`define INST_OPCODE_IL_LW `INST_FUNC3_WIDTH'b010
`define INST_OPCODE_IL_LBU `INST_FUNC3_WIDTH'b100
`define INST_OPCODE_IL_LHU `INST_FUNC3_WIDTH'b101

`define INST_OPCODE_S_TYPE `INST_OPCODE_WIDTH'b0100011
`define INST_OPCODE_S_SB `INST_FUNC3_WIDTH'b000
`define INST_OPCODE_S_SH `INST_FUNC3_WIDTH'b001
`define INST_OPCODE_S_SW `INST_FUNC3_WIDTH'b010

`define INST_OPCODE_B_TYPE `INST_OPCODE_WIDTH'b1100011
`define INST_OPCODE_B_BEQ `INST_FUNC3_WIDTH'b000
`define INST_OPCODE_B_BNE `INST_FUNC3_WIDTH'b001
`define INST_OPCODE_B_BLT `INST_FUNC3_WIDTH'b100
`define INST_OPCODE_B_BGE `INST_FUNC3_WIDTH'b101
`define INST_OPCODE_B_BLTU `INST_FUNC3_WIDTH'b110
`define INST_OPCODE_B_BGEU `INST_FUNC3_WIDTH'b111

`define INST_OPCODE_R_TYPE `INST_OPCODE_WIDTH'b0110011
//func7 00
`define INST_R_FUNC7_BASE_TYPE0 `INST_FUNC7_WIDTH'h0
`define INST_OPCODE_R_ADD `INST_FUNC3_WIDTH'b000
`define INST_OPCODE_R_XOR `INST_FUNC3_WIDTH'b100
`define INST_OPCODE_R_OR `INST_FUNC3_WIDTH'b110
`define INST_OPCODE_R_AND `INST_FUNC3_WIDTH'b111
`define INST_OPCODE_R_SLL `INST_FUNC3_WIDTH'b001
`define INST_OPCODE_R_SRL `INST_FUNC3_WIDTH'b101
`define INST_OPCODE_R_SLT `INST_FUNC3_WIDTH'b010
`define INST_OPCODE_R_SLTU `INST_FUNC3_WIDTH'b011
//func7 20
`define INST_R_FUNC7_BASE_TYPE1 `INST_FUNC7_WIDTH'h20
`define INST_OPCODE_R_SUB `INST_FUNC3_WIDTH'b000
`define INST_OPCODE_R_SRA `INST_FUNC3_WIDTH'b101
// func7 0x1
`define INST_R_FUNC7_MUL_TYPE `INST_FUNC7_WIDTH'h1
`define INST_OPCODE_R_MUL `INST_FUNC3_WIDTH'b000
`define INST_OPCODE_R_MULH `INST_FUNC3_WIDTH'b001
`define INST_OPCODE_R_MULSU `INST_FUNC3_WIDTH'b010
`define INST_OPCODE_R_MULU `INST_FUNC3_WIDTH'b011
`define INST_OPCODE_R_DIV `INST_FUNC3_WIDTH'b100
`define INST_OPCODE_R_DIVU `INST_FUNC3_WIDTH'b101
`define INST_OPCODE_R_REM `INST_FUNC3_WIDTH'b110
`define INST_OPCODE_R_REMU `INST_FUNC3_WIDTH'b111

`define INST_OPCODE_JAL_TYPE `INST_OPCODE_WIDTH'b1101111
`define INST_OPCODE_JALR_TYPE `INST_OPCODE_WIDTH'b1100111
`define INST_OPCODE_LUI_TYPE `INST_OPCODE_WIDTH'b0110111
`define INST_OPCODE_AUIPC_TYPE `INST_OPCODE_WIDTH'b0010111

`define INST_OPCODE_EI_TYPE `INST_OPCODE_WIDTH'b1110011
`define INST_OPCODE_EI_ECALL `INST_FUNC7_WIDTH'b0
`define INST_OPCODE_EI_EREAK `INST_FUNC7_WIDTH'b1
`define INST_OPCODE_EI_MRET `INST_FUNC7_WIDTH'h18

`define INST_OPCODE_ATOMIC_TYPE `INST_OPCODE_WIDTH'b0101111
`define INST_OPCODE_ATOMIC_LR `INST_FUNC5_WIDTH'h02
`define INST_OPCODE_ATOMIC_SC `INST_FUNC5_WIDTH'h03
`define INST_OPCODE_ATOMIC_SWAP `INST_FUNC5_WIDTH'h01
`define INST_OPCODE_ATOMIC_ADD `INST_FUNC5_WIDTH'h00
`define INST_OPCODE_ATOMIC_AND `INST_FUNC5_WIDTH'h0C
`define INST_OPCODE_ATOMIC_OR `INST_FUNC5_WIDTH'h0A
`define INST_OPCODE_ATOMIC_MAX `INST_FUNC5_WIDTH'h14
`define INST_OPCODE_ATOMIC_MIN `INST_FUNC5_WIDTH'h10

`define INST_CSR_WIDTH 12
`define INST_CSR_BASE 20
`define INST_OPCODE_CSR_TYPE `INST_OPCODE_WIDTH'b1110011
`define INST_OPCODE_CSR_CSRRW `INST_FUNC3_WIDTH'b001
`define INST_OPCODE_CSR_CSRRS `INST_FUNC3_WIDTH'b010
`define INST_OPCODE_CSR_CSRRC `INST_FUNC3_WIDTH'b011
`define INST_OPCODE_CSR_CSRRWI `INST_FUNC3_WIDTH'b101
`define INST_OPCODE_CSR_CSRRSI `INST_FUNC3_WIDTH'b110
`define INST_OPCODE_CSR_CSRRCI `INST_FUNC3_WIDTH'b111

`define INST_OPCODE_NOP_TYPE `INST_OPCODE_WIDTH'b0000001
`define INST_OPCODE_FENCE_TYPE  `INST_OPCODE_WIDTH'b0001111
`define INST_HOST_CPU_TYPE `INST_OPCODE_WIDTH'b0000000

`define CSR_CYCLE 12'hc00
`define CSR_CYCLEH 12'hc80
`define CSR_MTVEC 12'h305
`define CSR_MCAUSE 12'h342
`define CSR_MEPC 12'h341
`define CSR_MIE 12'h304
`define CSR_MSTATUS 12'h300
`define CSR_MSCRATCH 12'h340

`define INST_C_OP_BASE 0
`define INST_C_OP_WIDTH 2
`define INST_C_FUNC3_BASE 13
`define INST_C_FUNC3_WIDTH 3
`define INST_C_FUNC4_BASE 12
`define INST_C_FUNC4_WIDTH 4
`define INST_C_RS2_BASE 2
`define INST_C_RS2_WIDTH 5
`define INST_C_RS1_BASE 7
`define INST_C_RS1_WIDTH 5
`define INST_C_RD_BASE 7
`define INST_C_RD_WIDTH 5

`define DIV_OP_STOP 1'b0
`define DIV_OP_START 1'b1
`define INTERRUPT_MAX_NUM 2

`define EXCEPTION_CODE_WIDTH 12
// sync except
`define EXCEPTION_CODE_INSTRUCTION_ADDRESS_MISALIGNED `EXCEPTION_CODE_WIDTH'h0
`define EXCEPTION_CODE_INSTRUCTION_ACCESS_FAULT `EXCEPTION_CODE_WIDTH'h1
`define EXCEPTION_CODE_ILLEGAL_INSTRUCTION `EXCEPTION_CODE_WIDTH'h2
`define EXCEPTION_CODE_BREAKPOINT `EXCEPTION_CODE_WIDTH'h3
`define EXCEPTION_CODE_LOAD_ADDRESS_MISALIGNED `EXCEPTION_CODE_WIDTH'h4
`define EXCEPTION_CODE_LOAD_ADRESS_FAULT `EXCEPTION_CODE_WIDTH'h5
`define EXCEPTION_CODE_STORE_AMO_ADRESS_MISALIGNED `EXCEPTION_CODE_WIDTH'h6
`define EXCEPTION_CODE_STORE_AMO_ACCESS_FAULT `EXCEPTION_CODE_WIDTH'h7
`define EXCEPTION_CODE_ECALL_U_MODE `EXCEPTION_CODE_WIDTH'h8
`define EXCEPTION_CODE_ECALL_M_MODE `EXCEPTION_CODE_WIDTH'hb
`define EXCEPTION_CODE_STACK_OVERFLOW `EXCEPTION_CODE_WIDTH'h20
`define EXCEPTION_CODE_STACK_UNDER_FLOW `EXCEPTION_CODE_WIDTH'h21

//async except
`define EXCEPTION_CODE_SOFT_INT `EXCEPTION_CODE_WIDTH'h3
`define EXCEPTION_CODE_MTIMER_INT `EXCEPTION_CODE_WIDTH'h7
`define EXCEPTION_CODE_EXTERNAL_INT `EXCEPTION_CODE_WIDTH'hb

`define CPU_MODE_WIDTH 2
`define CPU_M_MODE `CPU_MODE_WIDTH'b11
`define CPU_S_MODE `CPU_MODE_WIDTH'b01
`define CPU_U_MODE `CPU_MODE_WIDTH'b00



`define ILM_ADDR_BASE `REG_WIDTH'h0
`define ILM_END_ADDR `REG_WIDTH'h4000

`define DLM_ADDR_BASE`REG_WIDTH'h4000
`define DLM_END_ADDR `REG_WIDTH'h8000

`define MTIMER_ADDR_BASE `REG_WIDTH'h20000000
`define MTIMER_END_ADDR `REG_WIDTH'h20001000

`define CLINT_ADDR_BASE `REG_WIDTH'h30000000
`define CLINT_END_ADDR `REG_WIDTH'h30001000
// flash 128k
`define FLASH_ADDR_BASE `REG_WIDTH'h80000000
`define FLASH_END_ADDR `REG_WIDTH'h80020000

`define UART_ADDR_BASE `REG_WIDTH'h90000000
`define UART_END_ADDR `REG_WIDTH'h90001000

`define INT_PROCESS_STATE_WIDTH 2
`define INT_PROCESS_STATE_START `INT_PROCESS_STATE_WIDTH'b01
`define INT_PROCESS_STATE_END `INT_PROCESS_STATE_WIDTH'b10

`define BUS_ADDR_WIDTH 32
`define BUS_ADDR_DATA_WIDTH 32
`define MST_ADDR_SEL_WIDTH 4
`define SLV_MAX_NUM 6
`define SLV0_ADDR_HI `MST_ADDR_SEL_WIDTH'h8
`define SLV1_ADDR_HI `MST_ADDR_SEL_WIDTH'h9
`define SLV2_ADDR_HI `MST_ADDR_SEL_WIDTH'ha
`define SLV3_ADDR_HI `MST_ADDR_SEL_WIDTH'hb
`define SLV4_ADDR_HI `MST_ADDR_SEL_WIDTH'hc
`define SLV5_ADDR_HI `MST_ADDR_SEL_WIDTH'hd

`define BUS_STATE_WIDTH 2
`define BUS_STATE_IDLE `BUS_STATE_WIDTH'b00
`define BUS_STATE_SETUP `BUS_STATE_WIDTH'b01
`define BUS_STATE_ENABLE `BUS_STATE_WIDTH'b10