$ROOT_PATH/rtl/core/defines.v
$ROOT_PATH/rtl/soc/tinyriscv_soc_top.v
$ROOT_PATH/rtl/debug/jtag_top.v
$ROOT_PATH/rtl/debug/jtag_dm.v
$ROOT_PATH/rtl/debug/jtag_driver.v
$ROOT_PATH/rtl/debug/uart_debug.v
$ROOT_PATH/rtl/core/tinyriscv.v
$ROOT_PATH/rtl/core/clint.v
$ROOT_PATH/rtl/core/csr_reg.v
$ROOT_PATH/rtl/core/ctrl.v
$ROOT_PATH/rtl/core/div.v
$ROOT_PATH/rtl/core/ex.v
$ROOT_PATH/rtl/core/id_ex.v
$ROOT_PATH/rtl/core/id.v
$ROOT_PATH/rtl/core/if_id.v
$ROOT_PATH/rtl/core/pc_reg.v
$ROOT_PATH/rtl/core/regs.v
$ROOT_PATH/rtl/core/rib.v
$ROOT_PATH/rtl/perips/gpio.v
$ROOT_PATH/rtl/perips/ram.v
$ROOT_PATH/rtl/perips/rom.v
$ROOT_PATH/rtl/perips/spi.v
$ROOT_PATH/rtl/perips/timer.v
$ROOT_PATH/rtl/perips/uart.v
$ROOT_PATH/rtl/utils/full_handshake_rx.v
$ROOT_PATH/rtl/utils/full_handshake_tx.v
$ROOT_PATH/rtl/utils/gen_buf.v
$ROOT_PATH/rtl/utils/gen_dff.v
